baseURL = "https://goxel.xyz/"
languageCode = "en-us"
title = "Goxel 3D Voxel Editor"

[params]
  lastReleaseVersion = "0.15.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
